### PR TITLE
Add information on custom containers.

### PR DESCRIPTION
**Pull request by edgonmsft**
Adding information on the incoming custom containers support.

### CODE REVIEW

**Comment by nikmd23** [comment]
The docs team (@conceptdev, @davidbritch & @profexorgeek) have been given access to this repo. They should also do a review before we merge this PR.

**Comment by davidbritch** [comment]
@nikmd23 I've edited the PR, so it's ready for your review/approval.

**Comment by davidbritch** [comment]
@nikmd23 

I'd also recommend the the H1 (page title) is updated. It's currently just "Configuring". If a user lands on that page from a search engine, they have to do a little extra work to discover what they are configuring. As a newcomer to these docs, I looked at the preview page and initially wondered what product this doc was for.

I guess the title should be something like "Configuring Visual Studio Online environments".

**Comment by nikmd23** [comment]
Great suggestion @davidbritch!

**Pull request merged**
