### PR TITLE
Added note for use as service as for example Alpine Linux is not supported

### PR DESCRIPTION
**Pull request by ntziolis**
Alpine Linux and many others

### CODE REVIEW

**Comment by gregvanl** [comment]
Thanks!

**Comment by ntziolis** [comment]
@gregvanl Do you have any idea how I can contact the team that builds the codespaces CLI? I have search quite a bit and cannot find a public repository related to this cli. The documentation page really is the only place so far I have found.

**Comment by gregvanl** [comment]
Hi @ntziolis I think you're in the right place. This repo is both for the Codespaces documentation and also product issues. If you have questions or suggestions for the Codespaces CLI, this would be the place to open an issue and start a discussion. If you review the open issues, you can see that most are related to the service or various clients and relatively few issues are for the documentation.

**Comment by ntziolis** [comment]
OK good to know so since this is related I'll ask in here. Are there any plans to provide an Alpine compatible service. Vscode / MS itself is using alpine as base for most of the suggested base images when creating a remote container.

Scenario:
- We use vscode + remote container feature to create dev containers on our own docker infrastructure
- And would like to use codespace feature to be able to connect to them without requiring a vpn connection
- **We are absolutely be happy to pay for this way of using codespaces**
  - I could imagine either packages (say up to x active codespaces x$ / month)
  - or by active codespace hour (could be minute but I think hour is acceptable and fair, day would not be. meaning active 5min pay for the day)
- But we have a fairly beefy internal docker infrastructure and cannot justify paying for cloud hosted developer machines while we have this hardware running idle. Im sure we are not the only ones in this situation

I think there is a market for extending this further:
- an agent to control the docker host that manages start/stopping of containers locally just like you provide for the cloud hosted containers + handling of code space registration

**Comment by abuchholtzau** [comment]
Hey @ntziolis,

Thank you so much for this amazing writeup of your feedback. We don't have current plans to support this scenario - for self-hosted, it wasn't built with registering a Docker image in mind. That said, we're always looking to solve the problems our customers need help with. I've filed an issue on behalf of you in our repo #666 - that way we can track community needs and best prioritize our backlog. Feel free to file any additional requests you think of in our [Issues](https://github.com/MicrosoftDocs/vscodespaces/issues).

**Pull request merged**
